# Generated by Django 5.2.14 on 2026-05-23 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_doctor_hospital_to_join(apps, schema_editor):
    """Carry every existing per-hospital Doctor row into HospitalDoctor before
    we strip the hospital/schedule/specialization/status fields off Doctor."""
    Doctor = apps.get_model('staff', 'Doctor')
    HospitalDoctor = apps.get_model('staff', 'HospitalDoctor')
    for doc in Doctor.objects.all():
        HospitalDoctor.objects.get_or_create(
            hospital_id=doc.hospital_id,
            doctor_id=doc.id,
            defaults={
                'specialization': doc.specialization or '',
                'schedule': doc.schedule or '',
                'status': doc.status or 'Active',
            },
        )


def reverse_noop(apps, schema_editor):
    # Reversing the data move isn't worth supporting — Doctor.hospital is being
    # restored as a non-null FK and we'd need to pick one HospitalDoctor row.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        # 1) Create the join table.
        migrations.CreateModel(
            name='HospitalDoctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(default='', max_length=200)),
                ('schedule', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_attachments', to='staff.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_attachments', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'staff_hospital_doctor',
                'ordering': ['-attached_at'],
                'unique_together': {('hospital', 'doctor')},
            },
        ),
        # 2) Add the new registry column.
        migrations.AddField(
            model_name='doctor',
            name='bmdc_registration_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        # 3) Carry existing data over BEFORE we drop the old columns.
        migrations.RunPython(copy_doctor_hospital_to_join, reverse_noop),
        # 4) Strip the per-hospital fields off Doctor now that they're saved on the join.
        migrations.RemoveField(model_name='doctor', name='hospital'),
        migrations.RemoveField(model_name='doctor', name='schedule'),
        migrations.RemoveField(model_name='doctor', name='specialization'),
        migrations.RemoveField(model_name='doctor', name='status'),
    ]
