# Generated by Django 5.2.14 on 2026-05-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_split_doctor_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=12),
        ),
    ]
