# Generated by Django 5.2.14 on 2026-05-23 13:21

from django.db import migrations, models


def lift_specialization_onto_doctor(apps, schema_editor):
    """Specialization is now a registry attribute (admin-owned). Roll the value
    up from each HospitalDoctor onto its Doctor before we drop the column.

    If a Doctor is attached to multiple hospitals with different specializations,
    take the first non-empty one — admin can tidy up afterwards."""
    Doctor = apps.get_model('staff', 'Doctor')
    HospitalDoctor = apps.get_model('staff', 'HospitalDoctor')
    for doc in Doctor.objects.all():
        if doc.specialization:
            continue
        match = (
            HospitalDoctor.objects.filter(doctor=doc)
            .exclude(specialization='')
            .first()
        )
        if match:
            doc.specialization = match.specialization
            doc.save(update_fields=['specialization'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_add_doctor_availability'),
    ]

    operations = [
        # 1) Add the new column on Doctor.
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        # 2) Carry data from the join onto the registry BEFORE we drop the join column.
        migrations.RunPython(lift_specialization_onto_doctor, reverse_noop),
        # 3) Drop the per-hospital specialization — it now lives on Doctor.
        migrations.RemoveField(
            model_name='hospitaldoctor',
            name='specialization',
        ),
    ]
