# Generated by Django 5.2.16 on 2026-09-13 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_alter_hospital_type'),
        ('staff', '0006_nurse_user_alter_nurse_hospital_medicalassistant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologist',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathologists', to='hospitals.hospital'),
        ),
    ]
