from django.urls import path
from .views import (
    OwnerDashboardView,
    CoOwnerListView, CoOwnerDetailView,
    ManagerListView, ManagerDetailView,
    PathologistListView, PathologistDetailView,
    DoctorListView, DoctorDetailView, DoctorRegistrySearchView,
    NurseListView, NurseDetailView, NurseAvailableSearchView, NurseImportView,
    MedicalAssistantListView, MedicalAssistantDetailView,
    MedicalAssistantAvailableSearchView, MedicalAssistantImportView,
    MidwifeListView, MidwifeDetailView, MidwifeAvailableSearchView, MidwifeImportView,
    BedListView, BedDetailView,
    LabTestListView, LabTestDetailView,
)

urlpatterns = [
    path('dashboard/', OwnerDashboardView.as_view(), name='owner-dashboard'),
    path('co-owners/', CoOwnerListView.as_view(), name='owner-co-owner-list'),
    path('co-owners/<uuid:pk>/', CoOwnerDetailView.as_view(), name='owner-co-owner-detail'),
    path('managers/', ManagerListView.as_view(), name='owner-manager-list'),
    path('managers/<uuid:pk>/', ManagerDetailView.as_view(), name='owner-manager-detail'),
    path('pathologists/', PathologistListView.as_view(), name='owner-pathologist-list'),
    path('pathologists/<uuid:pk>/', PathologistDetailView.as_view(), name='owner-pathologist-detail'),
    path('doctors/', DoctorListView.as_view(), name='owner-doctor-list'),
    path('doctors/search/', DoctorRegistrySearchView.as_view(), name='owner-doctor-registry-search'),
    path('doctors/<uuid:pk>/', DoctorDetailView.as_view(), name='owner-doctor-detail'),
    path('nurses/', NurseListView.as_view(), name='owner-nurse-list'),
    path('nurses/available/', NurseAvailableSearchView.as_view(), name='owner-nurse-available'),
    path('nurses/import/', NurseImportView.as_view(), name='owner-nurse-import'),
    path('nurses/<uuid:pk>/', NurseDetailView.as_view(), name='owner-nurse-detail'),
    path('medical-assistants/', MedicalAssistantListView.as_view(), name='owner-medical-assistant-list'),
    path('medical-assistants/available/', MedicalAssistantAvailableSearchView.as_view(), name='owner-medical-assistant-available'),
    path('medical-assistants/import/', MedicalAssistantImportView.as_view(), name='owner-medical-assistant-import'),
    path('medical-assistants/<uuid:pk>/', MedicalAssistantDetailView.as_view(), name='owner-medical-assistant-detail'),
    path('midwives/', MidwifeListView.as_view(), name='owner-midwife-list'),
    path('midwives/available/', MidwifeAvailableSearchView.as_view(), name='owner-midwife-available'),
    path('midwives/import/', MidwifeImportView.as_view(), name='owner-midwife-import'),
    path('midwives/<uuid:pk>/', MidwifeDetailView.as_view(), name='owner-midwife-detail'),
    path('beds/', BedListView.as_view(), name='owner-bed-list'),
    path('beds/<uuid:pk>/', BedDetailView.as_view(), name='owner-bed-detail'),
    path('lab-tests/', LabTestListView.as_view(), name='owner-labtest-list'),
    path('lab-tests/<uuid:pk>/', LabTestDetailView.as_view(), name='owner-labtest-detail'),
]
