# Generated by Django 5.2.16 on 2026-09-13 05:27

import apps.role_applications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('medical_assistant', 'Medical Assistant'), ('midwife', 'Midwife'), ('organization_owner', 'Organization Owner')], max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to=apps.role_applications.models.role_application_upload_path)),
                ('facility_photo', models.FileField(blank=True, null=True, upload_to=apps.role_applications.models.role_application_upload_path)),
                ('org_name', models.CharField(blank=True, default='', max_length=200)),
                ('org_type', models.CharField(blank=True, choices=[('Diagnostic', 'Diagnostic'), ('Clinic', 'Clinic'), ('Hospital', 'Hospital')], default='', max_length=20)),
                ('validity_till', models.DateField(blank=True, null=True)),
                ('org_phone', models.CharField(blank=True, default='', max_length=20)),
                ('location_text', models.CharField(blank=True, default='', max_length=300)),
                ('upazilla', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('division', models.CharField(blank=True, default='', max_length=100)),
                ('post_code', models.CharField(blank=True, default='', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_applications_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
