# Generated by Django 5.2.16 on 2026-09-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleapplication',
            name='role_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('medical_assistant', 'Medical Assistant'), ('midwife', 'Midwife'), ('pathologist', 'Pathologist'), ('organization_owner', 'Organization Owner')], max_length=30),
        ),
    ]
