# Generated by Django 5.2.14 on 2026-05-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='file_url',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/'),
        ),
    ]
