# Generated by Django 5.2.14 on 2026-05-23 11:02

import apps.patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_medicalreport_file_url_medicalreport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.patients.models.report_upload_path),
        ),
    ]
