# Generated by Django 5.2.14 on 2026-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_medicalreport_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hiv_status',
            field=models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive')], default='Negative', max_length=10),
        ),
    ]
