# Generated by Django 5.2.14 on 2026-05-23 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_hiv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportaccesslog',
            name='action',
            field=models.CharField(choices=[('searched', 'Searched'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('shared', 'Shared')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reportaccesslog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='patients.medicalreport'),
        ),
    ]
