# Generated by Django 5.2.14 on 2026-05-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_access_log_searched'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
