# Generated by Django 5.2.14 on 2026-05-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='conditions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
