# Generated by Django 5.2.16 on 2026-09-12 05:46

from django.db import migrations, models


def rename_hba1c_to_rbs(apps, schema_editor):
    HealthMetric = apps.get_model('patients', 'HealthMetric')
    HealthMetric.objects.filter(metric_type='hba1c').update(metric_type='rbs')


def rename_rbs_to_hba1c(apps, schema_editor):
    HealthMetric = apps.get_model('patients', 'HealthMetric')
    HealthMetric.objects.filter(metric_type='rbs').update(metric_type='hba1c')


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nid',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('rbs', 'RBS'), ('blood_pressure', 'Blood Pressure'), ('weight', 'Weight')], max_length=30),
        ),
        migrations.RunPython(rename_hba1c_to_rbs, rename_rbs_to_hba1c),
    ]
