# Generated by Django 4.2.13 on 2026-05-07 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_bn', models.CharField(max_length=300)),
                ('name_en', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('General', 'General'), ('Specialized', 'Specialized'), ('Clinic', 'Clinic'), ('Diagnostic', 'Diagnostic')], default='General', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused')], default='Active', max_length=10)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('beds', models.IntegerField(default=0)),
                ('established', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospitals_hospital',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='hospitals.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospitals_owner',
                'ordering': ['-created_at'],
            },
        ),
    ]
