# Generated by Django 5.2.16 on 2026-09-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(choices=[('General', 'General'), ('Specialized', 'Specialized'), ('Clinic', 'Clinic'), ('Diagnostic', 'Diagnostic'), ('Hospital', 'Hospital')], default='General', max_length=20),
        ),
    ]
